version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  create_vpc:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: Udagram-Project
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          name: Creating VPC
          command: |
           bash create.sh udagram-test udagram.yml udagramPrams.json
  launch_config:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: Udagram-Project
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          name: Running server launch configuration
          command: |
           bash create.sh udagramServer udagramServer.yml udagraServerPrams.json
      - run: sleep 90
 
workflows:
  aws-cli:
    jobs:
      - create_vpc
      - launch_config
          #context: aws