version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: Udagram-Project
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          name: List buckets from S3
          command: |
            echo "$TEST"
            echo "${TEST}"
            aws s3 ls
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
          #context: aws